name: Issue Translator

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: dromara/issues-translate-action@v1
        with:
          IS_MODIFY_TITLE: false
          CUSTOM_BOT_NOTE: "🤖 **Auto Translation**"
